### ISSUE TITLE
TLS connection issues

### ISSUE THREAD

**Issue by lmars** [flynn-archive/strowger#22]
When running strowger in flynn-demo, I am unable to communicate via TLS from either Ruby or the openssl cli.

I originally thought this was due to #8 but, unless I am mistaken, explicitly setting the version should work, but that doesn't seem to be the case.

Running this Ruby program:

https://gist.github.com/lmars/11221613

When using the default `SSLv23`:

```
$ ruby -v ssl.rb SSLv23
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
OpenSSL 1.0.1g 7 Apr 2014
ssl.rb:16:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
        from ssl.rb:16:in `<main>'
```

but I get a similar error with `SSLv3`:

```
$ ruby -v ssl.rb SSLv3
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
OpenSSL 1.0.1g 7 Apr 2014
ssl.rb:16:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server hello A (OpenSSL::SSL::SSLError)
        from ssl.rb:16:in `<main>'
```

Also, using `openssl s_client`:

```
$ openssl version
OpenSSL 1.0.1g 7 Apr 2014

$ openssl s_client -connect 127.0.0.1:8081
CONNECTED(00000003)
140735122276828:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:177:

---
no peer certificate available

---
No client certificate CA names sent

---
SSL handshake has read 0 bytes and written 517 bytes

---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE

---

$ openssl s_client -connect 127.0.0.1:8081 -ssl3
CONNECTED(00000003)
140735122276828:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:s3_pkt.c:596:

---
no peer certificate available

---
No client certificate CA names sent

---
SSL handshake has read 0 bytes and written 0 bytes

---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : SSLv3
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1398269804
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)

---
```

Using curl with `-k` works:

```
curl -k -v https://localhost:8081/keys
* About to connect() to localhost port 8081 (#0)
*   Trying 127.0.0.1...
* connected
* Connected to localhost (127.0.0.1) port 8081 (#0)
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES256-SHA
* Server certificate:
*        subject: O=Flynn
*        start date: 2014-04-23 16:01:53 GMT
*        expire date: 2015-04-23 16:01:53 GMT
*        subjectAltName: localhost matched
*        issuer: O=Flynn
*        SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /keys HTTP/1.1
> User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8x zlib/1.2.5
> Host: localhost:8081
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 23 Apr 2014 16:19:27 GMT
< 
Connection #0 to host localhost left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
```

Am I missing something glaringly obvious here?

**Comment by titanous** [comment]
It is indeed #8 you are running into. You need to use the `-no_ssl2` flag and the `-servername` flag (for SNI):

``` text
$ echo -e "quit\n" | openssl s_client -servername localhost -no_ssl2 -connect localhost:8081
CONNECTED(00000003)
depth=0 /O=Flynn
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 /O=Flynn
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/O=Flynn
   i:/O=Flynn
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIC6DCCAdKgAwIBAgIBADALBgkqhkiG9w0BAQUwEDEOMAwGA1UEChMFRmx5bm4w
HhcNMTQwNDIzMTYzMDQyWhcNMTUwNDIzMTYzMDQyWjAQMQ4wDAYDVQQKEwVGbHlu
bjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMr3tj/KWRG5haqod8pU
ROhZmfoZMrUnRBa6yGyxhBlkuPFz6fzgKV1xmcc54G94AlXQWeAAjaCeP9vNz1Ht
UCO+MDBaMCQaqMkds54hjZlPN+v5UiQVUO7y33IUbKGKEYHeMZ1yvYiYNcYtZw9J
CkBi70yNEh7IfUuOUiD7+fokJb1tlThPzCzEYiDEZMhmPyTHh52NTpzoogVDvMdo
SL7tjS4afItzBG4DUqVGcZNhrJ4b6a54UovScyiGUW8L/4kOTE2QUgP2iDpnk2b/
0B1ww3S/BDENsOOCpcaZ5q0A3z6kAShRSLMaIS+9RLCk+F28DNUNQ6KOkPnKeHGX
u0MCAwEAAaNRME8wDgYDVR0PAQH/BAQDAgCgMBMGA1UdJQQMMAoGCCsGAQUFBwMB
MAwGA1UdEwEB/wQCMAAwGgYDVR0RBBMwEYIJbG9jYWxob3N0hwR/AAABMAsGCSqG
SIb3DQEBBQOCAQEAauluUTdvUErhHq9tevW/Qu3/UglETrNmFN9PLvnR0xcB3RhU
WGaJnaKH6JyQ6YvqQa3C3TRaf2GR64xCeoJlurzczzsTlPIbJMUrOfNX1fFQEc4X
8kLg0NCV2A9OaLqUM1sUiqSrKhjpeiINVXhsarRh0RMs/TQeLnYQrMWrdrDQNxGe
lZK1nFXJeblNbUqZqKYKRouMcQSzPEZpBFXMWsGw/GD4iqyVeH0zUePRLVAVf6fo
MjaUiYRwgsjyzbucrqpRDtitN+zhb5QVQSvsONCbJhl++1042dZwGzWlwzJGCTHD
ofceDKvA2Iv8ZYNc55vepkpUVBkC7tTKAaIxrA==
-----END CERTIFICATE-----
subject=/O=Flynn
issuer=/O=Flynn
---
No client certificate CA names sent
---
SSL handshake has read 1003 bytes and written 444 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES256-SHA
    Session-ID: 2CFDE1F28109EE46E2063692DCB8AFA0A26A8CC88B7228E751F12F276997D7BE
    Session-ID-ctx:
    Master-Key: 7EA1ACE56656EDE4214DF14F1BCBD530990456821B3AD1715011D68149D6619510B04CEAF2D240C37069A27F3086D0C0
    Key-Arg   : None
    TLS session ticket:
    0000 - eb a7 f5 e5 31 41 f2 77-e2 19 83 c7 ba cd ee 61   ....1A.w.......a
    0010 - c6 66 df 92 f2 62 14 69-bc 65 37 dc d3 fb 5c 0d   .f...b.i.e7...\.
    0020 - b4 5e 98 be 51 87 a8 45-2c 12 21 3a 75 f9 bc 33   .^..Q..E,.!:u..3
    0030 - 21 e9 b0 73 2b c0 13 2d-bb 3f 9c 5b ce ad 50 0b   !..s+..-.?.[..P.
    0040 - f1 e0 87 df 76 0e a9 4d-53 bc e2 51 8a 00 eb 48   ....v..MS..Q...H
    0050 - ec 99 82 d4 b8 2d e8 9c-78 a4 1c d8 20 80 c4 e0   .....-..x... ...
    0060 - a7 27 2b b2 49 be 16 51-                          .'+.I..Q

    Start Time: 1398270898
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
DONE
```
